# Generated by Django 5.1.4 on 2025-02-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_generalcourseprice_assignment_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='admin_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('easy', 'easy'), ('middle', 'middle'), ('advanced', 'advanced')], default='easy', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('easy', 'easy'), ('middle', 'middle'), ('advanced', 'advanced')], max_length=32),
        ),
    ]
